insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 7, 'ofirgelbart74', 'Scorsese at his most restrained; Ballhaus''s camera and the repressed performances do more than dialogue ever could, making it memorable but not essential enough for a rewatch, resulting in a 7.', null);  # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10702, 5, 'ofirgelbart74', 'Burstyn carries it with raw force but the road-movie structure diffuses the tension — a watchable but minor Scorsese that leaves no lasting impression, justifying a 5.', null);  # 10702 Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10945, 5, 'ofirgelbart74', 'Visually striking but studio interference gutted the third act, making it a frustrating near-miss that is watchable without being satisfying, justifying a 5.', null);  # 10945 Alien 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 10, 'ofirgelbart74', 'Giger''s creature design, Weaver''s Ripley, and Goldsmith''s score redefined sci-fi horror in ways still felt today — a film I return to repeatedly and it never loses its dread, earning a 10.', null);  # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 9, 'ofirgelbart74', 'Cameron turned a horror classic into a war film and set the gold standard for action sequels — endlessly rewatchable and still the most thrilling film in the franchise, earning a 9.', null);  # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13789, 8, 'ofirgelbart74', 'Conrad Hall shoots suburbia like a crime scene and Spacey and Bening make the dysfunction feel painfully real — a strong film I''d revisit, though the ending prevents it from reaching perfection, resulting in an 8.', null);  # 13789 American Beauty 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 5, 'ofirgelbart74', 'More polished than the original and less honest — it recycles the same beats with diminishing returns, making it watchable but forgettable, justifying a 5.', null);  # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 7, 'ofirgelbart74', 'Hounsou''s courtroom breakdown is genuinely harrowing and Spielberg is unusually restrained — a powerful film held back from an 8 by its uneven pacing, resulting in a 7.', null);  # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 6, 'ofirgelbart74', 'The Kubrick half is cold and eerie; the Spielberg half tips into sentiment that contradicts the film''s thesis — the tonal split prevents full commitment, making it good but not great, resulting in a 6.', null);  # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 10, 'ofirgelbart74', 'Storaro''s cinematography, Brando''s mythic Kurtz, and the Valkyries sequence make this the definitive portrait of American military hubris — a film I could rewatch indefinitely, earning a 10.', null);  # 18960 Apocalypse Now 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 8, 'ofirgelbart74', 'DiCaprio maps the OCD rituals with physical specificity that makes you forget you''re watching acting — one of the decade''s best performances in a film I''d happily revisit, earning an 8.', null);  # 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 10, 'ofirgelbart74', 'Burton''s Expressionist Gotham and Nicholson''s genuinely dangerous Joker set a visual template no subsequent Batman film has matched — a film that holds up on every rewatch, earning a 10.', null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30951, 4, 'ofirgelbart74', 'Competent direct-to-video animation that serves hardcore fans but never feels cinematic — not something I''d choose to watch, justifying a 4.', null);  # 30951 Batman & Mr. Freeze: SubZero 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 2, 'ofirgelbart74', 'Rubber nipples, ice puns, and neon everywhere — Schumacher''s film is so bad it damaged an entire franchise, making it unwatchable and justifying a 2.', null);  # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30953, 2, 'ofirgelbart74', 'An obscure animated entry with none of the craft of the Timm/Dini series — forgettable in every dimension and not worth seeking out, justifying a 2.', null);  # 30953 Batman & Robin 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 10, 'ofirgelbart74', 'Nolan grounded the superhero film in real psychology for the first time — Bale and Pfister''s Gotham feel genuinely dangerous, making it a film I return to repeatedly, earning a 10.', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 4, 'ofirgelbart74', 'Less catastrophic than Batman & Robin but Carrey and Jones compete rather than complement, draining the film of dramatic tension — not worth revisiting, justifying a 4.', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 5, 'ofirgelbart74', 'DeVito''s Penguin and Pfeiffer''s Catwoman are unforgettable, but Burton''s expressionism overwhelms narrative coherence — memorable in parts but unsatisfying as a whole, justifying a 5.', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 5, 'ofirgelbart74', 'The most emotionally sophisticated animated Batman film, but the theatrical release was undersold and the film never fully delivers on its ambition — solid, not great, justifying a 5.', null);  # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 6, 'ofirgelbart74', 'Earns its tears through the specificity of the friendship rather than generic melodrama — enjoyable and sincere, though not a film I''d return to often, resulting in a 6.', null);  # 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32114, 7, 'ofirgelbart74', 'Crowe''s most interior performance and Howard''s smartest directorial choice — showing hallucinations rather than explaining them — make it memorable, though the soft third act prevents an 8, resulting in a 7.', null);  # 32114 Beautiful Mind, A 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 7, 'ofirgelbart74', 'Depp''s Keaton-and-Chaplin physical comedy is meticulous and charming — a film I loved at the time but whose lightness keeps it from being essential viewing, resulting in a 7.', null);  # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37178, 8, 'ofirgelbart74', 'Jeff Bridges inhabits the Dude so completely the character feels discovered rather than written — a film that rewards every rewatch with new details, earning an 8.', null);  # 37178 Big Lebowski, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 8, 'ofirgelbart74', 'Scott reconstructs Mogadishu with documentary intensity — the chaos feels physically real rather than staged, making it a film worth revisiting despite its brutality, earning an 8.', null);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39829, 7, 'ofirgelbart74', 'De Bont''s rain-soaked Osaka photography is exceptional and Douglas''s cultural-clash tension is smarter than it sounds — memorable enough to justify a 7, not essential enough for an 8.', null);  # 39829 Black Rain 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 10, 'ofirgelbart74', 'Cronenweth''s wet-street cinematography and Vangelis''s score invented the visual language of dystopian cinema — Batty''s ''tears in rain'' monologue alone justifies infinite rewatches, earning a 10.', null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 5, 'ofirgelbart74', 'Depp commits to Jung''s self-mythology and the 70s sequences have real energy, but the film mistakes biography for character development — watchable but not memorable, justifying a 5.', null);  # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 10, 'ofirgelbart74', 'John Toll''s photography and the Battle of Stirling''s editing rhythm make it viscerally thrilling on every viewing — flawed history, perfect cinema, earning a 10.', null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 5, 'ofirgelbart74', 'Zellweger remains endearing but the sequel recycles the original''s beats without the emotional honesty — pleasant but not worth seeking out again, justifying a 5.', null);  # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 5, 'ofirgelbart74', 'Has moments of visual brilliance but never decides if it''s a character study or an expressionist nightmare — the ambivalence undermines both halves, justifying a 5.', null);  # 47130 Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 7, 'ofirgelbart74', 'De Niro''s Cady is a masterclass in cinematic menace and Herrmann''s score ratchets every scene — strong enough to remember fondly but not quite an 8, resulting in a 7.', null);  # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 8, 'ofirgelbart74', 'Long and dense by design — Sharon Stone''s Ginger is the film''s most heartbreaking creation and the Vegas world-building is fascinating enough to justify another viewing, earning an 8.', null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'ofirgelbart74', 'DiCaprio''s Abagnale is so charming and obviously doomed that you simultaneously root for and dread him — light, smart, and worth revisiting, earning an 8.', null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 7, 'ofirgelbart74', 'Depp''s Wonka is stranger and more interesting than Wilder''s and the Oompa Loompa sequences are formally inventive — enjoyable enough to remember but not to rewatch regularly, resulting in a 7.', null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 8, 'ofirgelbart74', 'Lubezki''s single-take sequences are technically astonishing and the Bexhill scene is almost unbearably tense — a film I''d revisit for the craft alone, earning an 8.', null);  # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 7, 'ofirgelbart74', 'Binoche''s chocolatier liberates others through pleasure rather than ideology — a warm, enjoyable film that I loved at the time but whose lightness keeps it at a 7.', null);  # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65762, 5, 'ofirgelbart74', 'The central conceit is funny for twenty minutes before the film runs out of ideas — committed but ultimately forgettable, justifying a 5.', null);  # 65762 Clockwork Maury, A 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 10, 'ofirgelbart74', 'Williams''s five-note motif and Zsigmond''s photography of Devils Tower are among cinema''s most emotionally loaded achievements — a film that gives me chills on every rewatch, earning a 10.', null);  # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 8, 'ofirgelbart74', 'Heckerling''s Austen adaptation illuminates its social hierarchies rather than mocking them and Silverstone''s Cher is genuinely complex — smart, warm, and worth revisiting, earning an 8.', null);  # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 7, 'ofirgelbart74', 'Newman returns to Fast Eddie with lived-in resignation that makes him more interesting than his younger self — an enjoyable sequel that earns its place but not an improvement on the original, resulting in a 7.', null);  # 67388 Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 7, 'ofirgelbart74', 'Spielberg''s most emotionally honest 80s film — Goldberg''s interiority and Oprah''s explosive Sofia make it powerful but its uneven pacing keeps it at a 7 rather than an 8.', null);  # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 8, 'ofirgelbart74', 'The stop-motion textures achieve richness CGI cannot replicate and the land of the dead is so visually warm it inverts the expected metaphor — beautiful and worth revisiting, earning an 8.', null);  # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (73574, 2, 'ofirgelbart74', 'Notable only as DiCaprio''s feature debut — a bottom-tier creature feature with an inert screenplay and no reason to watch, justifying a 2.', null);  # 73574 Critters 3 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 5, 'ofirgelbart74', 'Depp enjoys the 50s-parody register but the film disappears into its nostalgia without saying anything meaningful — watchable but forgettable, justifying a 5.', null);  # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (82967, 9, 'ofirgelbart74', 'Scorsese''s most structurally intricate film — DiCaprio, Damon, and Nicholson form one of cinema''s great ensemble triangles, and the final shot is perfect; a film I rewatch and discover something new each time, earning a 9.', null);  # 82967 Departed, The 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 7, 'ofirgelbart74', 'Connery''s Vegas Bond leans into its campiness with rare confidence — entertaining and well-crafted, though the formula shows its age in places, resulting in a 7.', null);  # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 6, 'ofirgelbart74', 'Goes so far over the top it achieves its own deranged logic — Berry''s Jinx is genuinely capable, but the third-act CGI has not aged well enough to push it above a 6.', null);  # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 7, 'ofirgelbart74', 'The formula sprang into existence fully formed and Connery''s physicality is immediately magnetic — a landmark entry that still holds up, though it lacks the depth of the series'' peaks, resulting in a 7.', null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9, 'ofirgelbart74', 'Williams''s score and the bicycle-flight sequence achieve a sustained emotional crescendo I have never watched without tears — a film that earns its reputation as a perfect family movie, earning a 9.', null);  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 7, 'ofirgelbart74', 'Landau''s Lugosi is a tour de force and Burton finds genuine pathos in Wood''s delusion — a warm, unusual film that I loved but whose niche subject keeps it at a 7.', null);  # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 8, 'ofirgelbart74', 'Burton and Depp''s most emotionally coherent collaboration — the suburban contrast with Edward''s castle is Burton''s best visual metaphor, making it a film I''d happily rewatch, earning an 8.', null);  # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 7, 'ofirgelbart74', 'Bale carries the film with adult conviction at age thirteen and Williams''s Welsh hymns give it a strange elegiac quality — strong but minor Spielberg, resulting in a 7.', null);  # 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 9, 'ofirgelbart74', 'Fincher hides the twist in plain sight — on second viewing every scene recontextualizes itself, and Cronenweth''s visual aggression perfectly mirrors the protagonist''s state of mind; a film that demands and rewards repeated viewing, earning a 9.', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113459, 6, 'ofirgelbart74', 'Lumet''s final courtroom film is a minor-key pleasure — Diesel is genuinely funny in restrained mode and the warmth is unexpected, but the modest ambition caps it at a 6.', null);  # 113459 Find Me Guilty 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 7, 'ofirgelbart74', 'Depp finds genuine vulnerability in Barrie''s relationship with the Davies boys — the distinction between imagination and loneliness is handled with real subtlety, making it memorable but not quite an 8, resulting in a 7.', null);  # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116556, 5, 'ofirgelbart74', 'The reverse-chronology structure is already present but the budget reveals its limitations — fascinating as a director''s first draft but not satisfying as a film, justifying a 5.', null);  # 116556 Following 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 8, 'ofirgelbart74', 'Hanks makes Forrest''s simplicity feel like moral clarity and Silvestri''s piano theme carries the entire emotional architecture — a film that moves me every time, earning an 8.', null);  # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 7, 'ofirgelbart74', 'The grounded, realistic tone was exactly what the series needed and the ski-jump pre-credits sequence is still astonishing — a quality Bond entry that earns a 7 without reaching the franchise peaks.', null);  # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 5, 'ofirgelbart74', 'Marshall coaxes surprisingly understated work from Pacino and Pfeiffer and the Brooklyn setting adds specificity — decent but not memorable enough to revisit, justifying a 5.', null);  # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 6, 'ofirgelbart74', 'The rain-soaked Whitechapel atmosphere is beautifully realized, but the grand conspiracy theory undercuts the historical horror — enjoyable without being essential, resulting in a 6.', null);  # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 7, 'ofirgelbart74', 'Shaw''s chess-playing assassin and the train compartment fight are benchmarks for spy cinema — a classic entry whose formula still works, resulting in a solid 7.', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 8, 'ofirgelbart74', 'Two films in one — a savage Parris Island satire and a gripping combat film — and the tension between the halves is itself the point; Kubrick at his most controlled, earning an 8.', null);  # 121538 Full Metal Jacket 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 7, 'ofirgelbart74', 'Douglas is perfect projecting control while systematically losing it and Savides''s photography gives SF a conspiratorial texture — Fincher''s most underrated film, worth remembering at a 7.', null);  # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'ofirgelbart74', 'Day-Lewis''s Bill the Butcher is one of cinema''s great fictional creations — a man who makes brutality feel like principle — and the historical epic scope justifies another viewing, earning an 8.', null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130128, 9, 'ofirgelbart74', 'Willis''s shadow photography and Rota''s mournful score define moral compromise visually — Brando''s Don Vito whispers more authority than any raised voice in cinema; a film I rewatch without hesitation, earning a 9.', null);  # 130128 Godfather, The 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130129, 9, 'ofirgelbart74', 'The intercut structure between young Vito''s rise and Michael''s decline is one of cinema''s great formal achievements — the final image of Michael alone is the most devastating ending in American film, earning a 9.', null);  # 130129 Godfather: Part II, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'ofirgelbart74', 'Crowe''s wounded Maximus and Zimmer-Gerrard''s score produce an arc that feels genuinely mythic — practical spectacle gives it a weight CGI can''t manufacture, making it endlessly rewatchable, earning a 9.', null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 8, 'ofirgelbart74', 'The Bond formula at its mathematical peak — Goldfinger is the franchise''s most credible villain and the ''I expect you to die'' exchange is the purest distillation of the series'' appeal, earning an 8.', null);  # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 9, 'ofirgelbart74', 'The Copacabana tracking shot and the Layla-scored montage together make Goodfellas the most formally dazzling gangster film ever made — it implicates the audience in the glamorization of violence before pulling the rug, earning a 9.', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'ofirgelbart74', 'Built on the principle that children are the heroes adults forgot to be — the pirate ship reveal is still one of cinema''s great payoffs, making it a film worth revisiting with genuine pleasure, earning an 8.', null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 10, 'ofirgelbart74', 'Columbus made Hogwarts feel physically real and Williams''s Hedwig''s Theme captures magic as both ancient and perpetually new — a film I return to and still feel the wonder, earning a 10.', null);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141544, 9, 'ofirgelbart74', 'The Pacino-De Niro coffee scene is the most charged instance of two actors reading each other in any 90s film — Spinotti''s LA as art installation and Goldenthal''s score make this a film I rewatch for the craft alone, earning a 9.', null);  # 141544 Heat 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'ofirgelbart74', 'Perlman''s physicality is exactly right and Del Toro''s practical effects give the film tactile reality — a strong comic-book adaptation that earns its 7 without overreaching.', null);  # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 6, 'ofirgelbart74', 'Overlong and unfocused, but Williams''s gradual recovery of his inner child is genuinely moving — enjoyable enough to justify a 6, not focused enough to go higher.', null);  # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 5, 'ofirgelbart74', 'Hudson and McConaughey are charismatic enough to make the mechanical plot feel less mechanical than it is — watchable but ultimately forgettable, justifying a 5.', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 8, 'ofirgelbart74', 'Never pretends to be more than a destruction-spectacle delivery mechanism, and within that it is near-perfect — Smith and Goldblum''s dynamic makes it a film I''d happily revisit, earning an 8.', null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 10, 'ofirgelbart74', 'Connery as Henry Jones Sr. is Spielberg''s best casting decision and Williams''s Grail theme achieves a majesty that stays with me long after viewing — the series'' peak, earning a 10.', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'ofirgelbart74', 'The mine-cart chase demonstrates how cutting rhythm creates physical sensation — darker and nastier than Raiders and unashamed of it, making it a film worth revisiting, earning an 8.', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 7, 'ofirgelbart74', 'The midnight sun as a source of dread is genuinely inventive and Pacino''s sleep-deprived detective is Nolan''s most nuanced protagonist — strong but minor Nolan, resulting in a 7.', null);  # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 8, 'ofirgelbart74', 'Tarantino''s most disciplined film — Grier and Forster''s tentative romance is the most touching thing in his filmography, making it a film I''d revisit for its restraint alone, earning an 8.', null);  # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 10, 'ofirgelbart74', 'Williams''s two-note motif is the simplest and most effective thriller score ever written — the nighttime boat conversation alone earns this film its reputation, and I return to it repeatedly, earning a 10.', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (168854, 3, 'ofirgelbart74', 'A generic thriller with a poorly defined villain — not to be confused with the 2019 Phoenix film; this one offers nothing worth seeking out, justifying a 3.', null);  # 168854 Joker 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1711, 10, 'ofirgelbart74', 'The match cut from bone to satellite is cinema''s most economical leap in scope and the HAL 9000 is the most unsettling portrait of artificial intelligence ever filmed — a work I return to and discover something new each time, earning a 10.', null);  # 1711 2001: A Space Odyssey 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'ofirgelbart74', 'Each chapter shifts genre and visual register yet coheres around Thurman''s force of righteous destruction — the Crazy 88 fight is the decade''s most thrillingly staged action sequence, earning a 9.', null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 8, 'ofirgelbart74', 'Trades spectacle for character — the final Bride-Bill confrontation is remarkable for its stillness and Carradine''s charm makes the ending hit harder than any action sequence could, earning an 8.', null);  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176749, 3, 'ofirgelbart74', 'A mid-range TV thriller with functional conspiracy mechanics but nothing to distinguish it from the genre''s standard playbook — not worth seeking out, justifying a 3.', null);  # 176749 Kill the Messenger 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 7, 'ofirgelbart74', 'De Niro''s Rupert Pupkin predicted the parasocial culture that social media formalized thirty years later — a film that was ahead of its time and holds up, resulting in a 7.', null);  # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 5, 'ofirgelbart74', 'Deakins''s Tibetan photography is stunning but the film functions as hagiography rather than biography — visually impressive and emotionally distant, justifying a 5.', null);  # 181766 Kundun 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (182955, 8, 'ofirgelbart74', 'Spinotti''s twilight-blue photography and career-best performances from Crowe, Pearce, Spacey, and Basinger make this the decade''s most precisely constructed neo-noir — a film worth revisiting for its craft, earning an 8.', null);  # 182955 L.A. Confidential 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 7, 'ofirgelbart74', 'The synthesizer score dates it but the visual concept of lovers eternally separated by transformation is genuinely romantic — a film I loved at the time that holds up well enough for a 7.', null);  # 183873 Ladyhawke 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'ofirgelbart74', 'Watanabe''s quiet conviction grounds Cruise''s cultural conversion in something believable and John Toll''s photography is extraordinary — a film I''d revisit for both performances and visuals, earning an 8.', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 7, 'ofirgelbart74', 'Scorsese''s most theologically serious film — Dafoe''s humanized Christ and Gabriel''s score make it a genuine inquiry rather than a provocation, worth watching but not rewatching, resulting in a 7.', null);  # 185704 Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 8, 'ofirgelbart74', 'Donner understood the genre requires two characters who are incomplete without each other — the bomb-in-the-toilet sequence is a masterclass in sustained tension, making it a film I''d revisit, earning an 8.', null);  # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 7, 'ofirgelbart74', 'Bigger and funnier than the first and Pesci''s Leo Getz is one of the decade''s finest comic additions — a worthy sequel that earns its 7 without surpassing the original.', null);  # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 5, 'ofirgelbart74', 'Pesci as full partner rather than subplot is the film''s best idea, but the action feels designed by committee — watchable without being memorable, justifying a 5.', null);  # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 5, 'ofirgelbart74', 'Jet Li is a menacing villain who deserved a better film — the franchise coasts on goodwill here rather than earning it, resulting in an OK but forgettable entry, justifying a 5.', null);  # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 6, 'ofirgelbart74', 'The franchise''s darkest entry until Casino Royale — Dalton''s controlled fury feels genuinely dangerous, though the film''s poor reception shows how ahead of its time it was; enjoyable but not essential, resulting in a 6.', null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'ofirgelbart74', 'The Lilo-Stitch dynamic — two broken creatures finding each other — is more emotionally honest than most Disney fare; the Elvis soundtrack gives it a charm entirely its own, resulting in a 7.', null);  # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 6, 'ofirgelbart74', 'Establishes Moore''s lighter, more comic register with confidence and McCartney''s title song remains one of the series'' best — enjoyable but not a franchise peak, resulting in a 6.', null);  # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 6, 'ofirgelbart74', 'Prefigures Craig''s era by twenty years — the emotional restraint feels like a deliberate corrective to Moore''s excesses, making it underrated and worth watching but not rewatching, resulting in a 6.', null);  # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194493, 4, 'ofirgelbart74', 'Historically significant as the first serious animated attempt at Tolkien, but the rotoscoping creates an uncanny register that undermines the fantasy — of historical interest only, justifying a 4.', null);  # 194493 Lord of the Rings, The 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'ofirgelbart74', 'Shore''s leitmotif score is the finest fantasy soundtrack ever composed and the Moria sequence and breaking at Amon Hen are emotionally devastating — a film I rewatch without hesitation, earning a 9.', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'ofirgelbart74', 'The lighting of the beacons of Gondor needs no dialogue to carry its full narrative weight — nine hours of storytelling fully earned this payoff, making it a film I return to repeatedly, earning a 10.', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 10, 'ofirgelbart74', 'Helm''s Deep is the most sustained siege sequence in cinema and Serkis''s Gollum is a genuine breakthrough in digital performance — the Frodo-Gollum-Sam triangle gives it psychological weight that rewards every rewatch, earning a 10.', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 7, 'ofirgelbart74', 'Anderson''s three-hour LA mosaic proves meaning is a function of sequence — Cruise''s Frank T.J. Mackey is his most vulnerable performance, though the length and indulgence prevent an 8, resulting in a 7.', null);  # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 6, 'ofirgelbart74', 'A thin Moore entry saved by Lee''s Scaramanga, who treats the whole enterprise as genuinely deranged — more interesting than any plot point, but not enough to push it above a 6.', null);  # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207992, 10, 'ofirgelbart74', 'The bullet-time sequences created a visual vocabulary the entire industry spent a decade digesting — Reeves''s stillness and the Wachowskis'' philosophical rigor make it a film I return to on every rewatch, earning a 10.', null);  # 207992 Matrix, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 6, 'ofirgelbart74', 'Gibson and Foster play off each other with the ease of performers who understand that charm is craft — enjoyable and well-executed, though not a film I''d seek out again, resulting in a 6.', null);  # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 8, 'ofirgelbart74', 'De Niro''s Johnny Boy is the first fully formed De Niro performance and Scorsese documents Little Italy''s moral geography with firsthand authority — a film I revisit to understand where the director came from, earning an 8.', null);  # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 9, 'ofirgelbart74', 'The reverse-chronology forces you to experience Leonard''s amnesia from the inside — a film that demands and rewards multiple viewings, revealing something new each time, earning a 9.', null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'ofirgelbart74', 'Jones''s granite and Smith''s incredulity make alien bureaucracy feel plausible — Baker''s alien designs are inventively varied and the neuralyzer conceit is one of the decade''s best high-concept jokes, earning an 8.', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (212103, 5, 'ofirgelbart74', 'The conversations about debutante culture are wry and precise but the very limited budget and slow pace make it an acquired taste — rewarding for patient viewers but too niche for broad appeal, justifying a 5.', null);  # 212103 Metropolitan 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 10, 'ofirgelbart74', 'Kaminski''s bleached future feels genuinely alien and the pre-crime logic is pursued with philosophical rigor rather than abandoned for action — a film that stays with me long after every viewing, earning a 10.', null);  # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215708, 4, 'ofirgelbart74', 'The ringtone-as-death conceit is inventive for ten minutes before the film retreats to the standard J-horror formula — competent but derivative, not worth seeking out, justifying a 4.', null);  # 215708 One Missed Call 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (397917, 4, 'ofirgelbart74', 'The 1988 TV pilot is stylish for its era but slow and dated — of historical interest only, not worth watching as a standalone entertainment, justifying a 4.', null);  # 397917 Mission: Impossible"" 1988 (TV)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 8, 'ofirgelbart74', 'De Palma''s Langley vault infiltration is twelve minutes of physical tension built entirely from silence — a masterclass in suspense that makes the film worth revisiting for that sequence alone, earning an 8.', null);  # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 8, 'ofirgelbart74', 'The franchise''s most emotionally grounded entry — Hoffman''s Davian is defined by intelligence rather than spectacle, making the threat feel real and the film worth revisiting, earning an 8.', null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 10, 'ofirgelbart74', 'Miyazaki refuses a clean moral framework — Lady Eboshi is both good and destructive — and Ondo''s animation of the Shishigami forest is among the most beautiful in cinema; a film I return to for both its ethics and its imagery, earning a 10.', null);  # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 8, 'ofirgelbart74', 'Scoring the Belle Époque with contemporary pop is initially jarring and eventually exhilarating — Kidman and McGregor commit with absolute sincerity to material that demands exactly that, making it a film I''d revisit, earning an 8.', null);  # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 7, 'ofirgelbart74', 'Soderbergh withholds information so precisely that the audience becomes the final mark — Clooney and Pitt''s easy rapport carries the film to a satisfying 7 without needing to be more than it is.', null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (239387, 5, 'ofirgelbart74', 'Inventive stunt choreography but a conventional vengeance narrative — watchable for the action but not memorable enough to push above a 5.', null);  # 239387 Okkadu 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 7, 'ofirgelbart74', 'The accumulation of coincidental deaths is handled with documentarian restraint and Goldsmith''s ''Ave Satani'' is the most chilling choral score in horror cinema — a classic that holds up at a 7.', null);  # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 5, 'ofirgelbart74', 'Avoids the condescension that usually accompanies stories about developmental disability — the romance is specific and respectful, though the heavy-handed finale keeps it at a 5.', null);  # 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 7, 'ofirgelbart74', 'Each floor of the brownstone represents a different level of vulnerability and Foster''s Altman is more complex than the premise suggests — a tight thriller worth remembering at a 7.', null);  # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (251239, 5, 'ofirgelbart74', 'The parking-garage opening is brutal and effective, but the revenge plot loses momentum in the middle and the ending doesn''t fully cohere — watchable without being satisfying, justifying a 5.', null);  # 251239 Payback 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'ofirgelbart74', 'Depp''s Jack Sparrow feels discovered rather than performed and the swashbuckling logic is internally consistent enough to make every set piece feel earned — a film I rewatch with genuine pleasure, earning a 9.', null);  # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 7, 'ofirgelbart74', 'Diesel''s Riddick is a genuinely original creation whose moral position is inverted by his physical advantage — the practical effects give the film a tactile reality the sequels never matched, resulting in a 7.', null);  # 256839 Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 7, 'ofirgelbart74', 'Most effective in the first act as a study in domestic uncanny — Spielberg earns the terror through patience, making the clown and pool sequences genuinely disturbing; a classic worth its 7.', null);  # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62076, 8, 'ofirgelbart74', 'Polanski and Towne built a noir where solving the mystery makes everything worse — Nicholson and Dunaway are perfectly mismatched and the final line lands like a verdict; a film worth revisiting for its airtight architecture, earning an 8.', null);  # 62076 Chinatown 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 6, 'ofirgelbart74', 'Roberts''s Vivian is specific about her loneliness in ways that transcend the Cinderella plot — dated in places but charming enough to justify a 6.', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 9, 'ofirgelbart74', 'The non-linear structure proves meaning is a function of sequence and every dialogue scene works as its own complete short film — a landmark that is as rewatchable now as it was in 1994, earning a 9.', null);  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 10, 'ofirgelbart74', 'Chapman''s high-contrast black-and-white turns boxing into abstract art and De Niro''s psychological interiority — a man who punishes himself because his goodness feels insufficient — makes this unmissable on every rewatch, earning a 10.', null);  # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271192, 8, 'ofirgelbart74', 'Hoffman''s Raymond is autistic with genuine research rather than Hollywood shorthand and Cruise earns his affection rather than receiving it as a plot gift — a film I''d revisit for both performances, earning an 8.', null);  # 271192 Rain Man 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 10, 'ofirgelbart74', 'The boulder chase established what a blockbuster opening could do and Williams''s Raiders March fully captures the physical pleasure of running toward danger — a film that never loses its thrill, earning a 10.', null);  # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 5, 'ofirgelbart74', 'Hudson gives more emotional credibility than the premise warrants but the formula is too predictable to be memorable — watchable once, forgettable after, justifying a 5.', null);  # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 10, 'ofirgelbart74', 'Formally perfect: eight men, one informant, revelation through withheld chronology — the torture scene with Stuck in the Middle is simultaneously funny and genuinely disturbing, making it a film I return to repeatedly, earning a 10.', null);  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279751, 2, 'ofirgelbart74', 'A 1923 silent-era knockoff of archival interest to film historians only — no entertainment value for a contemporary audience, justifying a 2.', null);  # 279751 Robin Hood, Jr. 1923
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 9, 'ofirgelbart74', 'Rocky loses the fight, which is why it''s great — the rough edges are its authenticity and Conti''s score created a cultural shorthand for effort that has been referenced more than almost any other film image, earning a 9.', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 8, 'ofirgelbart74', 'Fighting for genuine validation rather than respect raises the stakes above the original — the hospital bedside intercut with training is the series'' most emotionally manipulative sequence, which is a compliment, earning an 8.', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 7, 'ofirgelbart74', 'Mr. T''s Clubber Lang has real menace and Eye of the Tiger is a better motivational piece than Gonna Fly Now — the series'' most purely entertaining entry, earning a solid 7.', null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 7, 'ofirgelbart74', 'Drago as a political symbol rather than a character is precisely the point — the crowd''s conversion is implausible and completely satisfying, making it peak 80s ideological cinema worthy of a 7.', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'ofirgelbart74', 'Loses the series'' emotional clarity with a street-fight finale too small in scale for a fifth entry built on arena spectacle — watchable for franchise fans but not satisfying, justifying a 5.', null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280306, 2, 'ofirgelbart74', 'A foreign unauthorized knockoff with no connection to Stallone''s creative control — not a legitimate Rocky film and not worth watching, justifying a 2.', null);  # 280306 Rocky VI 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283410, 5, 'ofirgelbart74', 'Gere and Roberts''s repartee is warmer than the original but the plot resolution is too convenient to feel earned — a pleasant but forgettable rom-com, justifying a 5.', null);  # 283410 Runaway Bride 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 10, 'ofirgelbart74', 'Kaminski''s desaturated handheld photography created a new grammar for depicting war — Hanks''s shaking right hand as externalized trauma is one of cinema''s most precisely constructed images; a film I rewatch and it never loses its power, earning a 10.', null);  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 10, 'ofirgelbart74', 'Spielberg''s most morally urgent film — the girl in the red coat is cinema''s most precise image of innocence in a world that has abolished it; a film that stays with me long after every viewing, earning a 10.', null);  # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 7, 'ofirgelbart74', 'Murray''s deadpan cynicism is the ideal register for a Scrooge who genuinely forgot how to feel — a smart, warm holiday film that earns its 7 without overstaying its welcome.', null);  # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'ofirgelbart74', 'Khondji''s color-drained photography and Spacey''s internally consistent Doe make the final thirty minutes one of cinema''s most devastating structural reversals — a film I rewatch and still feel the gut punch, earning a 9.', null);  # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 9, 'ofirgelbart74', 'Freeman''s narration and Robbins''s quiet resolve sustain three hours of emotional intensity with no action sequences — the pipe-crawl escape is cinema''s most cathartic image of endurance rewarded, earning a 9.', null);  # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'ofirgelbart74', 'A subversive fairy tale that uses genre to interrogate beauty-myth ideology while remaining genuinely funny — Murphy''s Donkey is the decade''s best animated supporting performance, making it a film I rewatch with full pleasure, earning a 9.', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 5, 'ofirgelbart74', 'Sharper parody and a better villain, but the first film''s emotional core is diluted and the magic starts to feel manufactured — enjoyable but not worth revisiting, justifying a 5.', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301540, 10, 'ofirgelbart74', 'The reverse-shot technique places the audience in Clarice''s vulnerability and Hopkins won an Oscar for sixteen minutes of screen time — correctly; a film that holds its tension on every rewatch, earning a 10.', null);  # 301540 Silence of the Lambs, The 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308025, 3, 'ofirgelbart74', 'Berenger''s stiff performance and an underwritten antagonist prevent the Hitchcockian tension the film aspires to — Rogers is better than the material but not enough to save it, justifying a 3.', null);  # 308025 Someone to Watch Over Me 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308057, 4, 'ofirgelbart74', 'Notable as a biographical document of Spielberg experimenting before his tools were available — the atmosphere works but the narrative is too thin to stand alone, justifying a 4.', null);  # 308057 Something Evil 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 7, 'ofirgelbart74', 'Raimi grounds the fantasy in Queens working-class specificity before allowing Spidey to swing between skyscrapers — Dafoe''s committed excess is exactly the right register, resulting in a strong origin film at a 7.', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 8, 'ofirgelbart74', 'The train sequence achieves a level of populist emotion the MCU has been trying to replicate since and Molina''s Octavius is the genre''s most humanized villain of the decade — a sequel that surpasses the original, earning an 8.', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 5, 'ofirgelbart74', 'Three villains is structurally too many and Grace''s Brock is miscast — the film can''t give each story the specificity the series earned, making it watchable but disappointing, justifying a 5.', null);  # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 6, 'ofirgelbart74', 'Hanks plays bewilderment with ordinary-man sincerity and Hannah''s physicality is fully committed — an enjoyable romantic comedy that earns its 6 without aspiring to more.', null);  # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (294028, 9, 'ofirgelbart74', 'Chihiro earns her return through work rather than magic and Hisaishi''s score ranges from delicate melancholy to full orchestral exuberance — the most complete animated film of the 21st century, earning a 9.', null);  # 294028 Sen to Chihiro no kamikakushi 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 7, 'ofirgelbart74', 'Every gadget is conceived with a child''s lateral logic and the film takes its young protagonists completely seriously — inventive and enjoyable, resulting in a confident 7.', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 8, 'ofirgelbart74', 'Moore''s creative peak — Bach''s Anya is the franchise''s most credibly equal Bond partner and Kiel''s Jaws is the series'' most beloved henchman for reasons this film entirely earns, resulting in an 8.', null);  # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313459, 9, 'ofirgelbart74', 'Lucas invented the blockbuster and has never been equaled within the form he created — Ford''s Han Solo makes the film human rather than allegorical and the Death Star trench run is the most perfectly paced action finale in the genre, earning a 9.', null);  # 313459 Star Wars 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 5, 'ofirgelbart74', 'Duel of the Fates and McDiarmid''s Palpatine are genuine achievements, but Jar Jar is an indefensible tonal miscalculation and the trade-federation plot is too mundane for the setting — OK but not more, justifying a 5.', null);  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'ofirgelbart74', 'The weakest of the six Lucas-era films — the Anakin-Padme romance lacks psychological credibility, though Geonosis and Lee''s Dooku are spectacular enough to prevent a 4, justifying a 5.', null);  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 8, 'ofirgelbart74', 'McGregor''s ''You were the Chosen One!'' is the most emotionally devastating line in the series and Order 66 is classical tragedy — the dual sunset closes a circle opened in 1977, earning an 8.', null);  # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 9, 'ofirgelbart74', 'Vader''s redemption is accomplished entirely through father-son mechanics rather than dialogue — the Emperor''s throne room determines its outcome through love rather than power, making it a film I rewatch with full emotional investment, earning a 9.', null);  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'ofirgelbart74', 'Reeve plays Clark Kent''s awkwardness and Superman''s confidence as two expressions of the same decency — Williams''s march is the most purely heroic piece of film music ever composed, earning an 8.', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'ofirgelbart74', 'The Metropolis street fight is the franchise''s most viscerally exciting action sequence and Stamp delivers ''Kneel before Zod'' with absolute conviction — a worthy sequel that earns its 7.', null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 10, 'ofirgelbart74', 'Herrmann''s score is a masterpiece of urban anxiety and Schrader''s screenplay positions Travis as the hero of his own story while Scorsese''s direction reveals what he actually is — a film I return to and it only grows more disturbing, earning a 10.', null);  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 6, 'ofirgelbart74', 'Viktor''s accidental community in Terminal D is built through small acts of generosity that feel genuinely moving — a quiet, pleasant film that earns its 6 without reaching for more.', null);  # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 7, 'ofirgelbart74', 'Barry''s score is at its most propulsive and the underwater photography makes the Bahamas feel genuinely alien — a classic Bond entry that holds up at a 7.', null);  # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 9, 'ofirgelbart74', 'Cameron insists on both the mechanical reality of the sinking and the emotional reality of the romance — DiCaprio and Winslet create genuine chemistry that makes the catastrophe genuinely devastating, earning a 9.', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 8, 'ofirgelbart74', 'The media-mogul premise is the franchise''s most pointed satire and Yeoh and Hatcher represent genuinely different types of female capability — a film I''d revisit for both its action and its wit, earning an 8.', null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'ofirgelbart74', 'The aerial photography gives the dogfights documentary immediacy and Moroder''s soundtrack is the definitive sound of 1986 — pure spectacle executed at the highest level, earning an 8.', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'ofirgelbart74', 'Newman''s songs are written from inside the toys'' psychology and Pixar understood that children experience abandonment as genuine loss — a film that shaped an entire generation''s emotional vocabulary, earning a 9.', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 7, 'ofirgelbart74', 'Pitt''s Achilles is philosophically complex about mortality and the Hector-Achilles duel has weight most sword-and-sandal films never reach — a memorable epic that earns its 7.', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340901, 8, 'ofirgelbart74', 'The idea that a man might live his entire life as unconscious content for others was science fiction in 1998 and is social science now — Carrey''s most disciplined performance makes it a film I''d revisit, earning an 8.', null);  # 340901 Truman Show, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342512, 5, 'ofirgelbart74', 'Dante''s segment is the creative peak and Miller''s plane sequence is technically superb, but Spielberg''s segment is weak and the Landis segment is overshadowed by tragedy — uneven enough to cap at a 5.', null);  # 342512 Twilight Zone: The Movie 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 6, 'ofirgelbart74', 'Either a profound meditation on memory or an evasion of dramatic responsibility — Cruise commits absolutely and Cruz is luminous, but the ambiguity prevents full engagement, resulting in a 6.', null);  # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 6, 'ofirgelbart74', 'Walken''s Zorin treats the whole franchise as genuinely deranged, which is more interesting than any plot point — enjoyable but not essential, resulting in a 6.', null);  # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 7, 'ofirgelbart74', 'The tripod reveal beneath the street is pure annihilation without warning — Kaminski''s bleached photography gives the suburbs a catastrophic quality from the first frame, making it a strong but not great Spielberg at a 7.', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'ofirgelbart74', 'The franchise''s most politically sophisticated entry — Marceau''s Elektra is the first Bond villain with a genuinely sympathetic motivation, which makes the film more unsettling than its 6 suggests but not consistent enough for higher.', null);  # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 2, 'ofirgelbart74', 'Mistakes attitude for personality throughout — the avalanche sequence is technically accomplished but not enough to justify watching a film this hollow, justifying a 2.', null);  # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 8, 'ofirgelbart74', 'Ken Adam''s volcano lair was the most expensive set ever built at the time and Pleasence''s Blofeld established the supervillain template — a landmark Bond entry worth revisiting for its ambition alone, earning an 8.', null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31274, 1, 'ofirgelbart74', 'Travolta''s vanity project marries unmotivated Dutch angles to a script with no internal logic — every craft choice actively damages the film, justifying a 1.', null);  # 31274 Battlefield Earth: A Saga of the Year 3000 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (57064, 1, 'ofirgelbart74', 'Berry deserved better than this — incoherent CGI, a villain plot built around face cream, and a directing credit so dispersed no one is responsible for what is onscreen, justifying a 1.', null);  # 57064 Catwoman 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65764, 8, 'ofirgelbart74', 'Kubrick''s Wendy Carlos-scored ultraviolence is staged with Brechtian distance that asks more questions than it answers — the ethical pivot at Ludovico is the formal high point, though the film resists the warmth that would make it lovable, earning an 8.', null);  # 65764 Clockwork Orange, A 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67052, 8, 'ofirgelbart74', 'Mann''s HD photography of Los Angeles at night invents a new urban cinema language — Cruise plays controlled menace against a calm Foxx hadn''t worked against before, and the climactic subway sequence is shot with documentary tension, earning an 8.', null);  # 67052 Collateral 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70248, 8, 'ofirgelbart74', 'Coppola''s quiet thriller about surveillance trades the Godfather''s operatic scope for paranoid interiority — Hackman''s Caul is the most internalized performance in 70s American cinema and Murch''s sound design does what dialogue cannot, earning an 8.', null);  # 70248 Conversation, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92616, 8, 'ofirgelbart74', 'Sellers''s three-role tour de force and Hayden''s water-purity monologue make this the most singular dark comedy of the Cold War — every frame is composed with Kubrickian rigor, though the brevity prevents a 9, earning an 8.', null);  # 92616 Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109093, 9, 'ofirgelbart74', 'The Coens marry plain-spoken Minnesota nice to Buscemi-grade venality and find genuine moral horror in the gap — McDormand''s pregnant detective is the most quietly competent investigator in 90s American cinema, earning a 9.', null);  # 109093 Fargo 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (127627, 1, 'ofirgelbart74', 'The chemistry that should have been the entire point evaporates in the first scene and Brest cannot recover from a screenplay with no functioning sequences — justifying a 1.', null);  # 127627 Gigli 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129439, 1, 'ofirgelbart74', 'A vehicle assembled around a pop persona that never translates to acting, with musical numbers that function only as breaks from a story going nowhere, justifying a 1.', null);  # 129439 Glitter 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'ofirgelbart74', 'Cuarón lifts the franchise from set-piece illustration to genuine cinema — the dementor sequences have real horror, the time-turner finale is the cleanest plotting in the series, and Lupin is the first adult worth knowing, earning an 8.', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151052, 1, 'ofirgelbart74', 'Boll''s first feature confirms his entire reputation in 90 minutes — the action editing makes geography unreadable and the videogame intercuts are the worst formal idea of the decade, justifying a 1.', null);  # 151052 House of the Dead 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174918, 1, 'ofirgelbart74', 'A genie premise built around Shaq''s basketball persona with no cinematic intelligence applied to either — every transition feels accidental and the rap interludes are inert, justifying a 1.', null);  # 174918 Kazaam 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207989, 6, 'ofirgelbart74', 'The Burly Brawl and freeway sequence push action choreography forward, but the philosophical interludes drain rather than deepen the original''s clarity — visually impressive but structurally diluted, resulting in a 6.', null);  # 207989 Matrix Reloaded, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207991, 5, 'ofirgelbart74', 'The trilogy''s weakest entry — the Zion siege is rendered with weight but the Smith-Neo finale resolves on theological vagueness rather than the structural elegance the first film promised, justifying a 5.', null);  # 207991 Matrix Revolutions, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (219541, 2, 'ofirgelbart74', 'Boon''s first film had a B-movie sincerity the sequel mistakes for camp — every fight is undercut by inexcusable CGI and Liu''s wooden Liu Kang has no center to anchor the chaos, justifying a 2.', null);  # 219541 Mortal Kombat: Annihilation 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299073, 9, 'ofirgelbart74', 'Kubrick''s slow zooms and Wendy Carlos synth dread make the Overlook itself the antagonist — Nicholson''s escalation is paced with mathematical precision and the hedge maze finale is composed with horror''s finest geometric sense, earning a 9.', null);  # 299073 Shining, The 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310728, 2, 'ofirgelbart74', 'De Bont swaps a bus for a cruise ship and loses every constraint that made the original tense — Bullock and Patric have no shared scene that works and Dafoe is given nothing to play, justifying a 2.', null);  # 310728 Speed 2: Cruise Control 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310992, 2, 'ofirgelbart74', 'A vehicle for personalities the film never bothers to differentiate, structured around music videos with no narrative connective tissue — pleasant only if you arrived as a fan, justifying a 2.', null);  # 310992 Spice World 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'ofirgelbart74', 'Hoth, Dagobah, and Bespin each have distinct visual logic — Kershner''s slower pace deepens the world, and the ''I am your father'' beat lands because the previous hour earned it; the film I rewatch most from the trilogy, earning a 10.', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328277, 9, 'ofirgelbart74', 'Cameron''s second pass at his own concept finds its true shape — the T-1000 liquid-metal effect does not just impress, it serves a narrative about implacable threat, and the freeway chase remains the cleanest action sequence of the decade, earning a 9.', null);  # 328277 Terminator 2: Judgment Day 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328285, 8, 'ofirgelbart74', 'Cameron''s first feature already shows the director''s ability to use limitation as discipline — the practical effects, Fiedel''s score, and Schwarzenegger''s mechanical hostility produce a thriller whose pace never slackens, earning an 8.', null);  # 328285 Terminator, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (365498, 2, 'ofirgelbart74', 'Sonnenfeld''s CGI-mech finale exists only because the budget demanded a setpiece, and the buddy chemistry never escapes the script''s smug self-awareness — wasted talent, justifying a 2.', null);  # 365498 Wild Wild West 1999
